### ISSUE TITLE
02_clustering.ipynb - raises error in code cell 3

### ISSUE THREAD

**Issue by subrockmann** [iubh/DLMDSML01#1]
The code cell 3 in "02_clustering.ipynb" raises an error. The content of the code cell is 
`features: 2 dimensional `
and does not provide any useful information for the rest of the notebook.

I recommend to remove this code cell.

**Comment by m-Pak** [comment]
Thanks for pointing that out. The content of the code cell "# features: 2 dimensional" is just a comment added during the Q&A session. Since it is a comment (#) it should not raise an error.
